# 基础镜像
FROM nginx
# author
MAINTAINER slf

# 挂载目录
VOLUME /home/slf/projects/slf-ui
# 创建目录
RUN mkdir -p /home/slf/projects/slf-ui
# 指定路径
WORKDIR /home/slf/projects/slf-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/slf/projects/slf-ui
